#!/usr/bin/env python3

import json
import sys

def f(row):
    return 3600*int(row[0]) + 60*int(row[1]) + int(row[2].split(".")[0]) + int(row[2].split(".")[1])/100

def t(data):
    return sum(f(r) for r in data)

print(json.dumps(t(json.load(sys.stdin))))
